"""A ReAct (reason + act) loop built explicitly with LangGraph."""

from react_loop.chat import ChatSession, Command, parse_command, run_chat
from react_loop.console import (
    get_console,
    print_error,
    print_trace,
    setup_logging,
)
from react_loop.graph import (
    DEFAULT_SYSTEM_PROMPT,
    build_react_graph,
    should_continue,
)
from react_loop.llm import ReActModel, ScriptedChatModel, build_llm
from react_loop.runner import ReActRunner, final_answer, run_react, trace
from react_loop.market_state import MarketStateManager
from react_loop.alerts import (
    AlertScheduler,
    EmailNotifier,
    MemoryNotifier,
    WebhookNotifier,
)
from react_loop.market_data import (
    CachedMarketDataService,
    FallbackMarketDataProvider,
    MarketDataCache,
    MarketDataError,
    MarketDataProvider,
    MarketEvent,
    PriceBar,
    Quote,
    SourceInfo,
)
from react_loop.state import AgentState
from react_loop.streaming import (
    FinalEvent,
    ReActStreamRunner,
    TokenEvent,
    ToolCallEvent,
    ToolResultEvent,
)
from react_loop.tools import (
    ALL_TOOLS,
    calculator,
    get_current_time,
    search_knowledge_base,
    stock_market_data,
    stock_technicals,
    resolve_stock_symbol,
    stock_fundamentals,
    compare_stocks,
    stock_backtest,
    evaluate_forecast_probabilities,
    sec_filings,
    earnings_history,
    earnings_calendar,
    market_calendar,
    market_cache_status,
    clear_market_cache,
    web_search,
    wikipedia_search,
    wikipedia_summary,
)

__all__ = [
    "ALL_TOOLS",
    "AlertScheduler",
    "CachedMarketDataService",
    "FallbackMarketDataProvider",
    "EmailNotifier",
    "MarketDataCache",
    "MarketDataError",
    "MarketDataProvider",
    "MarketEvent",
    "MemoryNotifier",
    "PriceBar",
    "Quote",
    "SourceInfo",
    "WebhookNotifier",
    "DEFAULT_SYSTEM_PROMPT",
    "AgentState",
    "MarketStateManager",
    "ChatSession",
    "Command",
    "FinalEvent",
    "ReActModel",
    "ReActRunner",
    "ReActStreamRunner",
    "ScriptedChatModel",
    "TokenEvent",
    "ToolCallEvent",
    "ToolResultEvent",
    "build_llm",
    "build_react_graph",
    "calculator",
    "final_answer",
    "get_console",
    "get_current_time",
    "parse_command",
    "print_error",
    "print_trace",
    "run_chat",
    "run_react",
    "search_knowledge_base",
    "setup_logging",
    "should_continue",
    "stock_market_data",
    "stock_technicals",
    "resolve_stock_symbol",
    "stock_fundamentals",
    "compare_stocks",
    "stock_backtest",
    "evaluate_forecast_probabilities",
    "sec_filings",
    "earnings_history",
    "earnings_calendar",
    "market_calendar",
    "market_cache_status",
    "clear_market_cache",
    "trace",
    "web_search",
    "wikipedia_search",
    "wikipedia_summary",
]

__version__ = "0.1.0"
